spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://lee38138:Bachkhoa12@lee01.dkroxft.mongodb.net/planb?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: planBGroup
    topic: planb-events
server:
  port: 8080